### ISSUE TITLE
0.9.x-dev break application

### ISSUE THREAD

**Issue by giovannicandido** [FriendsOfSymfony/FOSRest#18]
The latest update does not reconize the app/config.yml options:

format_listener:
           default_priorities: [html, 'json', '_/_']
           fallback_format: html
           prefer_extension: false

Causing the error:

Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "default_priorities, fallback_format, prefer_extension" under "fos_rest.format_listener"' in /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:316 Stack trace: #0 /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(268): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #1 /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(308): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #2 /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(268): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #3 /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(33): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #4 /var/www/icei/vendor/symfon in /var/www/icei/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 316

**Comment by giovannicandido** [comment]
I resolve change the config.yml to:

``` yaml
 format_listener:
      rules:
         - { path: '^/', priorities: ['html','json', 'xml'], fallback_format: json, prefer_extension: false }
         - { path: '^/image', priorities: ['jpeg', 'gif'], fallback_format: jpeg, prefer_extension: true }
         - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
```
