### ISSUE TITLE
Broken getHeaders

### ISSUE THREAD

**Issue by marapper** [FriendsOfSymfony/FOSRest#9]
After new commits overloaded ViewHandler was broken.

Notice: Trying to get property of non-object in /home/sergey/web/vr-as/vendor/bundles/FOS/RestBundle/View/View.php line 338 

``` yaml
    #services.yml
    ironsoft_vras.jsonp_handler:
            class: %ironsoft_vras.jsonp_handler.class%
            arguments:
                container: "@serializer"
                logger: "@?logger"


    ironsoft_vras.vras_view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'js', [@ironsoft_vras.jsonp_handler, 'createResponse'] ] ]
```

``` php
     #Controller.php
     $this->get('fos_rest.view_handler')->handle($view)
```

``` php
  #JsonpViewHandler
  class JsonpViewHandler {
     ...
    public function createResponse(ViewHandler $handler, View $view, Request $request, $format)
    {
       $content = $this->jsonEncode($view->getData());
       $code = $view->getStatusCode();
        ...
        return new Response($content, $code, $view->getHeaders());
       }
```
